// AUTO-GENERATED by tern-codegen from the "tern" manifest in package.json.
// Do not edit — change the manifest and re-run `yarn gen`.

/** IRI identifying this package as a Tern extension. */
export const MENUS_EXTENSION_IRI = "urn:sys:ui:menus" as const;

/**
 * Static identity for this extension, derived from its manifest.
 *
 * Spread this into the package's hand-written extension object so identity has a
 * single source:
 *
 *     export const menusExtension = {
 *         ...menusExtensionDescriptor,
 *         async install(ctx) { ... },
 *     };
 */
export const menusExtensionDescriptor = {
    /** Extension IRI — the stable identity used by the host and the marketplace. */
    iri: MENUS_EXTENSION_IRI,
    /** npm package name that ships this extension. */
    name: "@jasonscharf/ui-menus",
    /** Package version, used as the extension version. */
    version: "0.1.0",
    /** Extension IRIs that must be installed before this one. */
    requires: ["urn:sys:core"],
    /** Ontology files this extension owns, relative to the package root. */
    ontologies: ["./ontology/menus.ttl"],
} as const;

/** Static shape of this extension's generated identity. */
export type MenusExtensionDescriptor = typeof menusExtensionDescriptor;
