# Patch: replace the base emptyDir redis-data volume with the PVC.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
